### ISSUE TITLE
Please add force FP authentication after reboot feature. Thanks

### ISSUE THREAD

**Issue by saikat0511** [DerpLab/platform_packages_apps_DerpQuest#3]

**Comment by idoybh** [comment]
No way. This feature is not secure. And before you say it has a toggle, the toggle is in user space and can be easily manipulated with ADB.  My recommendation is to stay encrypted. An unlocked bootloader and root are enough of a security breach. At least if someone finds / steals your phone you would want him to wipe it before he can use it.
