### ISSUE TITLE
Error building...

### ISSUE THREAD

**Issue by saikat0511** [DerpLab/platform_packages_apps_DerpQuest#5]
FAILED: /home/saikat/derp_ten/out/target/common/obj/APPS/Settings_intermediates/flat-res/packages/app
s/DerpQuest/res/values_derpquest_strings.arsc.flat
/bin/bash -c "/home/saikat/derp_ten/out/host/linux-x86/bin/aapt2 compile -o /home/saikat/derp_ten/out
/target/common/obj/APPS/Settings_intermediates/flat-res/packages/apps/DerpQuest/res/ --pseudo-localiz
e --legacy packages/apps/DerpQuest/res/values/derpquest_strings.xml"
packages/apps/DerpQuest/res/values/derpquest_strings.xml:576: error: duplicate value for resource 'st
ring/action_save' with config ''.
packages/apps/DerpQuest/res/values/derpquest_strings.xml:576: error: resource previously defined here
.
packages/apps/DerpQuest/res/values/derpquest_strings.xml: error: file failed to compile.

**Comment by saikat0511** [comment]
reverted the latest omni doze commit now working fine

**Comment by saikat0511** [comment]
nope another error

FAILED: /home/saikat/derp_ten/out/target/product/kenzo/obj/APPS/Settings_intermediates/package-res.apk /home/saikat/derp_ten/out/target/common/obj/APPS/Settings_intermediates/aapt2.srcjar /home/saikat/der
p_ten/out/target/common/obj/APPS/Settings_intermediates/extra_packages /home/saikat/derp_ten/out/target/common/obj/APPS/Settings_intermediates/src/R.stamp /home/saikat/derp_ten/out/target/common/obj/APPS/
Settings_intermediates/proguard_options
/bin/bash /home/saikat/derp_ten/out/target/product/kenzo/obj/APPS/Settings_intermediates/package-res.apk.rsp
warn: removing resource com.android.settings:string/network_traffic_hidearrow without required default value.
warn: removing resource com.android.settings:string/network_traffic_hidearrow_summary without required default value.
packages/apps/DerpQuest/res/values/derpquest_arrays.xml:481: error: resource string/DESC_LIGHT_IDLE_AFTER_INACTIVE_TIMEOUT (aka com.android.settings:string/DESC_LIGHT_IDLE_AFTER_INACTIVE_TIMEOUT) not foun
d.
packages/apps/DerpQuest/res/values/derpquest_arrays.xml:482: error: resource string/DESC_LIGHT_PRE_IDLE_TIMEOUT (aka com.android.settings:string/DESC_LIGHT_PRE_IDLE_TIMEOUT) not found.
packages/apps/DerpQuest/res/values/derpquest_arrays.xml:483: error: resource string/DESC_LIGHT_IDLE_TIMEOUT (aka com.android.settings:string/DESC_LIGHT_IDLE_TIMEOUT) not found.
packages/apps/DerpQuest/res/values/derpquest_arrays.xml:484: error: resource string/DESC_LIGHT_IDLE_FACTOR (aka com.android.settings:string/DESC_LIGHT_IDLE_FACTOR) not found.
packages/apps/DerpQuest/res/values/derpquest_arrays.xml:485: error: resource string/DESC_LIGHT_MAX_IDLE_TIMEOUT (aka com.android.settings:string/DESC_LIGHT_MAX_IDLE_TIMEOUT) not found.
packages/apps/DerpQuest/res/values/derpquest_arrays.xml:486: error: resource string/DESC_LIGHT_IDLE_MAINTENANCE_MIN_BUDGET (aka com.android.settings:string/DESC_LIGHT_IDLE_MAINTENANCE_MIN_BUDGET) not foun
d.
packages/apps/DerpQuest/res/values/derpquest_arrays.xml:487: error: resource string/DESC_LIGHT_IDLE_MAINTENANCE_MAX_BUDGET (aka com.android.settings:string/DESC_LIGHT_IDLE_MAINTENANCE_MAX_BUDGET) not foun
d.
packages/apps/DerpQuest/res/values/derpquest_arrays.xml:488: error: resource string/DESC_MIN_LIGHT_MAINTENANCE_TIME (aka com.android.settings:string/DESC_MIN_LIGHT_MAINTENANCE_TIME) not found.
packages/apps/DerpQuest/res/values/derpquest_arrays.xml:489: error: resource string/DESC_MIN_DEEP_MAINTENANCE_TIME (aka com.android.settings:string/DESC_MIN_DEEP_MAINTENANCE_TIME) not found.
packages/apps/DerpQuest/res/values/derpquest_arrays.xml:490: error: resource string/DESC_INACTIVE_TIMEOUT (aka com.android.settings:string/DESC_INACTIVE_TIMEOUT) not found.
packages/apps/DerpQuest/res/values/derpquest_arrays.xml:491: error: resource string/DESC_SENSING_TIMEOUT (aka com.android.settings:string/DESC_SENSING_TIMEOUT) not found.
packages/apps/DerpQuest/res/values/derpquest_arrays.xml:492: error: resource string/DESC_LOCATING_TIMEOUT (aka com.android.settings:string/DESC_LOCATING_TIMEOUT) not found.
packages/apps/DerpQuest/res/values/derpquest_arrays.xml:493: error: resource string/DESC_LOCATION_ACCURACY (aka com.android.settings:string/DESC_LOCATION_ACCURACY) not found.
packages/apps/DerpQuest/res/values/derpquest_arrays.xml:494: error: resource
OTION_INACTIVE_TIMEOUT) not found.
_PENDING_TIMEOUT) not found.
packages/apps/DerpQuest/res/values/derpquest_arrays.xml:497: error: resource string/DESC_MAX_IDLE_PENDING_TIMEOUT (aka com.android.settings:string/DESC_MAX_IDLE_PENDING_TIMEOUT) not found.
packages/apps/DerpQuest/res/values/derpquest_arrays.xml:498: error: resource string/DESC_IDLE_PENDING

**Comment by rahul9999xda** [comment]
> FAILED: /home/saikat/derp_ten/out/target/common/obj/APPS/Settings_intermediates/flat-res/packages/app
> s/DerpQuest/res/values_derpquest_strings.arsc.flat
> /bin/bash -c "/home/saikat/derp_ten/out/host/linux-x86/bin/aapt2 compile -o /home/saikat/derp_ten/out
> /target/common/obj/APPS/Settings_intermediates/flat-res/packages/apps/DerpQuest/res/ --pseudo-localiz
> e --legacy packages/apps/DerpQuest/res/values/derpquest_strings.xml"
> packages/apps/DerpQuest/res/values/derpquest_strings.xml:576: error: duplicate value for resource 'st
> ring/action_save' with config ''.
> packages/apps/DerpQuest/res/values/derpquest_strings.xml:576: error: resource previously defined here
> .
> packages/apps/DerpQuest/res/values/derpquest_strings.xml: error: file failed to compile.

Remove line 576

**Comment by idoybh** [comment]
Compiles fine

**Comment by saikat0511** [comment]
deleted derpquest package and checked out again now is fine... must be some sync issues
